name: Frontend Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from package.json
        run: |
          VERSION=$(grep -E '"version": "[^"]+"' package.json | awk -F'"' '{print $4}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'

      - name: Install Dependencies
        run: npm install

      - name: Build and Test
        run: npm run build
        env:
          ci: true

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: mastilovic/rk-frontend
          tags: ${{ env.VERSION }}, latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.event_name == 'push'
